menu:
  工具: /apps
  关于: /about
rss: /atom.xml
description: 
social:
  weibo: 
  github: https://github.com/cylin2000
  stack_overflow: 
  facebook: 
  twitter: https://twitter.com/cylin2000
  google_plus: 
  email: cylin2000@163.com

page_comment: true
logo: /img/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-blue

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

valine_app_id : 
valine_app_secret : 

google_analytics: 
baidu_tongji: 
favicon: /img/favicon.png

#mathjax
mathjax: true

# 'Read more' button
excerpt_link: 继续阅读

# Footer message
site_license: 本站点采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>
theme_message: 由 <a href="http://hexo.io">Hexo</a> 强力驱动，使用 <a href="https://github.com/cylin2000/hexo-theme-vno ">Vno</a> 主题

